### ISSUE TITLE
Core Sets Break the Bot

### ISSUE THREAD

**Issue by skeet70** [skeet70/mtgpricebot#3]
```
heroku logs                                                                                         ~/c/mtgprice
2015-04-22T19:16:53.119647+00:00 app[bot.1]: 
2015-04-22T19:16:53.119652+00:00 app[bot.1]: Welcome to Willie. Loading modules...
2015-04-22T19:16:53.123267+00:00 app[bot.1]: 
2015-04-22T19:16:53.123374+00:00 app[bot.1]: 
2015-04-22T19:16:53.125051+00:00 app[bot.1]: Connecting to irc.globalgamers.net:6667...
2015-04-22T19:16:53.119653+00:00 app[bot.1]: 
2015-04-22T19:16:53.119772+00:00 app[bot.1]: 
2015-04-22T19:16:53.123003+00:00 app[bot.1]: 
2015-04-22T19:16:53.123007+00:00 app[bot.1]: 
2015-04-22T19:16:53.123140+00:00 app[bot.1]: Registered 4 modules,
2015-04-22T19:16:53.123265+00:00 app[bot.1]: 0 modules failed to load
2015-04-22T22:44:11.040698+00:00 app[bot.1]: Name and set passed in, try getting them directly.
2015-04-22T22:44:11.110118+00:00 app[bot.1]: Constructing a name based on time warp
2015-04-22T22:44:11.109716+00:00 app[bot.1]: Getting card: time warp M10
2015-04-22T22:44:11.111722+00:00 app[bot.1]: Constructing an ID from Time_Warp and M10
2015-04-22T22:44:11.111315+00:00 app[bot.1]: Constructing a set based on M10
2015-04-22T22:44:11.111519+00:00 app[bot.1]: Found M10 in set_symbols, passing through.
2015-04-22T22:44:11.365784+00:00 app[bot.1]: Found M10 in set_symbols, passing through.
2015-04-22T22:44:11.368671+00:00 app[bot.1]: Constructing a set based on M10
2015-04-22T22:44:11.369270+00:00 app[bot.1]: Loading set: M10
2015-04-22T22:44:11.368916+00:00 app[bot.1]: Found M10 in set_symbols, passing through.
2015-04-22T22:44:11.364684+00:00 app[bot.1]: Card not found in cache: time warp M10
2015-04-22T22:44:11.367942+00:00 app[bot.1]: Set not found in cache: M10
2015-04-22T22:44:11.377075+00:00 app[bot.1]:   File "/app/modules/price.py", line 256, in get_card
2015-04-22T22:44:11.365392+00:00 app[bot.1]: Constructing a set based on M10
2015-04-22T22:44:11.368314+00:00 app[bot.1]: Set M10 wasn't found, caching and trying again.
2015-04-22T22:44:11.366410+00:00 app[bot.1]: Checking if set M10 exists in the cache.
2015-04-22T22:44:11.377072+00:00 app[bot.1]:   File "/app/modules/price.py", line 307, in price
2015-04-22T22:44:11.377094+00:00 app[bot.1]:     set_name = set_symbols[set.upper()]
2015-04-22T22:44:11.377064+00:00 app[bot.1]: Traceback (most recent call last):
2015-04-22T22:44:11.377096+00:00 app[bot.1]: AttributeError: type object 'set' has no attribute 'upper'
2015-04-22T22:44:11.377097+00:00 app[bot.1]: Exception while searching: 
2015-04-22T22:44:11.377074+00:00 app[bot.1]:     card = get_card(name, set_name)
2015-04-22T22:44:11.377077+00:00 app[bot.1]:     load_set(construct_set(set_name))
2015-04-22T22:44:11.377078+00:00 app[bot.1]:   File "/app/modules/price.py", line 185, in load_set
2015-04-22T22:44:50.698271+00:00 app[bot.1]: Only card name given: Stoke the Flames attempting to fuzzy match set.
2015-04-22T22:44:50.754263+00:00 app[bot.1]: Getting card: omniscience M13
2015-04-22T22:44:50.754525+00:00 app[bot.1]: Constructing a name based on omniscience
2015-04-22T22:44:50.754908+00:00 app[bot.1]: Constructing a set based on M13
2015-04-22T22:44:50.755389+00:00 app[bot.1]: Constructing an ID from Omniscience and M13
2015-04-22T22:44:50.755149+00:00 app[bot.1]: Found M13 in set_symbols, passing through.
2015-04-22T22:44:50.814851+00:00 app[bot.1]:     data = requests.get('https://api.deckbrew.com/mtg/cards?'+urllib.urlencode({'name': input_name})).json()
2015-04-22T22:44:50.814984+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests/api.py", line 55, in get
2015-04-22T22:44:50.815431+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests/api.py", line 44, in request
2015-04-22T22:44:50.815311+00:00 app[bot.1]:     return request('get', url, **kwargs)
2015-04-22T22:44:50.815572+00:00 app[bot.1]:     return session.request(method=method, url=url, **kwargs)
2015-04-22T22:44:50.816122+00:00 app[bot.1]:     resp = self.send(prep, **send_kwargs)
2015-04-22T22:44:50.816241+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 486, in send
2015-04-22T22:44:50.816406+00:00 app[bot.1]:     r = adapter.send(request, **kwargs)
2015-04-22T22:44:50.806308+00:00 app[bot.1]: Traceback (most recent call last):
2015-04-22T22:44:50.815695+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 383, in request
2015-04-22T22:44:50.816537+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests/adapters.py", line 385, in send
2015-04-22T22:44:50.814566+00:00 app[bot.1]:     card, fuzzy_name, fuzzy_set = get_deckbrew(options[0])
2015-04-22T22:44:50.814714+00:00 app[bot.1]:   File "/app/modules/price.py", line 267, in get_deckbrew
2015-04-22T22:44:50.818553+00:00 app[bot.1]:     raise SSLError(e)
2015-04-22T22:44:50.818978+00:00 app[bot.1]: Exception while searching: 
2015-04-22T22:44:50.818713+00:00 app[bot.1]: SSLError: hostname 'api.deckbrew.com' doesn't match either of 'ssl2000.cloudflare.com', 'cloudflare.com', '*.cloudflare.com'
2015-04-22T22:44:50.833792+00:00 app[bot.1]: Card not found in cache: omniscience M13
2015-04-22T22:44:50.834111+00:00 app[bot.1]: Constructing a set based on M13
2015-04-22T22:44:50.837267+00:00 app[bot.1]: Set M13 wasn't found, caching and trying again.
2015-04-22T22:44:50.834535+00:00 app[bot.1]: Found M13 in set_symbols, passing through.
2015-04-22T22:44:50.837019+00:00 app[bot.1]: Set not found in cache: M13
2015-04-22T22:44:50.839232+00:00 app[bot.1]:     load_set(construct_set(set_name))
2015-04-22T22:44:50.838100+00:00 app[bot.1]: Loading set: M13
2015-04-22T22:44:50.838825+00:00 app[bot.1]:   File "/app/modules/price.py", line 307, in price
2015-04-22T22:44:50.839095+00:00 app[bot.1]:   File "/app/modules/price.py", line 256, in get_card
2015-04-22T22:44:50.838971+00:00 app[bot.1]:     card = get_card(name, set_name)
2015-04-22T22:44:50.837467+00:00 app[bot.1]: Constructing a set based on M13
2015-04-22T22:44:50.837864+00:00 app[bot.1]: Found M13 in set_symbols, passing through.
2015-04-22T22:44:50.839355+00:00 app[bot.1]:   File "/app/modules/price.py", line 185, in load_set
2015-04-22T22:44:50.838684+00:00 app[bot.1]: Traceback (most recent call last):
2015-04-22T22:44:50.839624+00:00 app[bot.1]: AttributeError: type object 'set' has no attribute 'upper'
2015-04-22T22:44:50.839857+00:00 app[bot.1]: Exception while searching: 
2015-04-22T22:44:50.839488+00:00 app[bot.1]:     set_name = set_symbols[set.upper()]
2015-04-22T22:44:50.750372+00:00 app[bot.1]: Name and set passed in, try getting them directly.
2015-04-22T22:44:50.810302+00:00 app[bot.1]:   File "/app/modules/price.py", line 321, in price
2015-04-22T22:44:50.834899+00:00 app[bot.1]: Checking if set M13 exists in the cache.
2015-04-22T22:44:55.299656+00:00 app[bot.1]: Set M15 wasn't found, caching and trying again.
2015-04-22T22:44:55.173089+00:00 app[bot.1]: Name and set passed in, try getting them directly.
2015-04-22T22:44:55.299888+00:00 app[bot.1]: Constructing a set based on M15
2015-04-22T22:44:55.300123+00:00 app[bot.1]: Found M15 in set_symbols, passing through.
2015-04-22T22:44:55.300356+00:00 app[bot.1]: Loading set: M15
2015-04-22T22:44:55.300994+00:00 app[bot.1]: Traceback (most recent call last):
2015-04-22T22:44:55.174962+00:00 app[bot.1]: Found M15 in set_symbols, passing through.
2015-04-22T22:44:55.175190+00:00 app[bot.1]: Constructing an ID from Stoke_the_Flames and M15
2015-04-22T22:44:55.297906+00:00 app[bot.1]: Card not found in cache: Stoke the Flames M15
2015-04-22T22:44:55.298107+00:00 app[bot.1]: Constructing a set based on M15
2015-04-22T22:44:55.298608+00:00 app[bot.1]: Checking if set M15 exists in the cache.
2015-04-22T22:44:55.299407+00:00 app[bot.1]: Set not found in cache: M15
2015-04-22T22:44:55.174169+00:00 app[bot.1]: Getting card: Stoke the Flames M15
2015-04-22T22:44:55.174392+00:00 app[bot.1]: Constructing a name based on Stoke the Flames
2015-04-22T22:44:55.298342+00:00 app[bot.1]: Found M15 in set_symbols, passing through.
2015-04-22T22:44:55.301166+00:00 app[bot.1]:   File "/app/modules/price.py", line 307, in price
2015-04-22T22:44:55.301305+00:00 app[bot.1]:     card = get_card(name, set_name)
2015-04-22T22:44:55.301424+00:00 app[bot.1]:   File "/app/modules/price.py", line 256, in get_card
2015-04-22T22:44:55.301569+00:00 app[bot.1]:     load_set(construct_set(set_name))
2015-04-22T22:44:55.301705+00:00 app[bot.1]:   File "/app/modules/price.py", line 185, in load_set
2015-04-22T22:44:55.301815+00:00 app[bot.1]:     set_name = set_symbols[set.upper()]
2015-04-22T22:44:55.301945+00:00 app[bot.1]: AttributeError: type object 'set' has no attribute 'upper'
2015-04-22T22:44:55.302396+00:00 app[bot.1]: Exception while searching: 
2015-04-22T22:44:55.174735+00:00 app[bot.1]: Constructing a set based on M15
```

Anyone feel like taking a crack at this?

**Comment by skeet70** [comment]
Fixed in 8527d13a8c
