### ISSUE TITLE
Planar_Chaos

### ISSUE THREAD

**Issue by skeet70** [skeet70/mtgpricebot#7]
``` irc
2015-05-08T19:25:23.679596+00:00 app[bot.1]: Getting card: Damnation PLC
2015-05-08T19:25:23.680092+00:00 app[bot.1]: Found PLC in set_symbols, passing through.
2015-05-08T19:25:23.758028+00:00 app[bot.1]: Card not found in cache: Damnation PLC
2015-05-08T19:25:23.758456+00:00 app[bot.1]: Checking if set Planar_Chaos exists in the cache.
2015-05-08T19:25:23.803215+00:00 app[bot.1]: Set not found in cache: Planar_Chaos
2015-05-08T19:25:23.680234+00:00 app[bot.1]: Constructing an ID from Damnation and Planar_Chaos
2015-05-08T19:25:23.758166+00:00 app[bot.1]: Constructing a set based on PLC
2015-05-08T19:25:23.805642+00:00 app[bot.1]: Found PLC in set_symbols, passing through.
2015-05-08T19:25:23.678980+00:00 app[bot.1]: Name and set passed in, try getting them directly.
2015-05-08T19:25:23.805478+00:00 app[bot.1]: Constructing a set based on PLC
2015-05-08T19:25:23.805784+00:00 app[bot.1]: Loading set: Planar_Chaos
2015-05-08T19:25:23.806684+00:00 app[bot.1]: Calling mtgprice API for set: Planar_Chaos
2015-05-08T19:25:23.805296+00:00 app[bot.1]: Set PLC wasn't found, caching and trying again.
2015-05-08T19:25:24.163747+00:00 app[bot.1]: Loading JSON from MTGPrice for: Planar_Chaos
2015-05-08T19:25:24.166628+00:00 app[bot.1]: Caching card list for: Planar_Chaos
2015-05-08T19:25:24.441600+00:00 app[bot.1]:   File "/app/modules/price.py", line 202, in load_set
2015-05-08T19:25:24.441684+00:00 app[bot.1]:     options={"expires_in": 86400, "add": True}
2015-05-08T19:25:24.441754+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/iron_cache.py", line 128, in put
2015-05-08T19:25:24.441857+00:00 app[bot.1]:     {"Content-Type": "application/json"})
2015-05-08T19:25:24.441257+00:00 app[bot.1]:   File "/app/modules/price.py", line 309, in price
2015-05-08T19:25:24.441357+00:00 app[bot.1]:     card = get_card(name, set_name)
2015-05-08T19:25:24.438148+00:00 app[bot.1]: Traceback (most recent call last):
2015-05-08T19:25:24.441433+00:00 app[bot.1]:   File "/app/modules/price.py", line 258, in get_card
2015-05-08T19:25:24.441518+00:00 app[bot.1]:     load_set(construct_set(set_name))
2015-05-08T19:25:24.442144+00:00 app[bot.1]:     retry=retry)
2015-05-08T19:25:24.442181+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/iron_core.py", line 245, in request
2015-05-08T19:25:24.442270+00:00 app[bot.1]:     r.raise_for_status()
2015-05-08T19:25:24.442359+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests/models.py", line 773, in raise_for_status
2015-05-08T19:25:24.442436+00:00 app[bot.1]:     raise HTTPError(http_error_msg, response=self)
2015-05-08T19:25:24.442521+00:00 app[bot.1]: HTTPError: 404 Client Error: Not Found
2015-05-08T19:25:24.442691+00:00 app[bot.1]: Exception while searching: 
2015-05-08T19:25:24.441943+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/iron_core.py", line 330, in put
2015-05-08T19:26:55.166815+00:00 app[bot.1]:   File "/app/modules/price.py", line 269, in get_deckbrew
2015-05-08T19:26:55.094495+00:00 app[bot.1]: Only card name given: weed-eater line for black&decker gh3000 attempting to fuzzy match set.
2015-05-08T19:26:55.166676+00:00 app[bot.1]:   File "/app/modules/price.py", line 323, in price
2015-05-08T19:26:55.166910+00:00 app[bot.1]:     data = requests.get('https://api.deckbrew.com/mtg/cards?'+urllib.urlencode({'name': input_name})).json()
2015-05-08T19:26:55.167005+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests/api.py", line 55, in get
2015-05-08T19:26:55.166745+00:00 app[bot.1]:     card, fuzzy_name, fuzzy_set = get_deckbrew(options[0])
2015-05-08T19:26:55.167263+00:00 app[bot.1]:     return session.request(method=method, url=url, **kwargs)
2015-05-08T19:26:55.167109+00:00 app[bot.1]:     return request('get', url, **kwargs)
2015-05-08T19:26:55.167811+00:00 app[bot.1]:     raise SSLError(e)
2015-05-08T19:26:55.168052+00:00 app[bot.1]: Exception while searching: 
2015-05-08T19:26:55.167897+00:00 app[bot.1]: SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
2015-05-08T19:26:55.167471+00:00 app[bot.1]:     resp = self.send(prep, **send_kwargs)
2015-05-08T19:26:55.167553+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 486, in send
2015-05-08T19:26:55.167177+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests/api.py", line 44, in request
2015-05-08T19:26:55.167350+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 383, in request
2015-05-08T19:26:55.167641+00:00 app[bot.1]:     r = adapter.send(request, **kwargs)
2015-05-08T19:26:55.167709+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests/adapters.py", line 385, in send
2015-05-08T19:26:55.166481+00:00 app[bot.1]: Traceback (most recent call last):
2015-05-08T19:27:48.004538+00:00 app[bot.1]: Set PLC wasn't found, caching and trying again.
2015-05-08T19:27:48.005434+00:00 app[bot.1]: Loading set: Planar_Chaos
2015-05-08T19:27:48.004767+00:00 app[bot.1]: Constructing a set based on PLC
2015-05-08T19:27:47.946435+00:00 app[bot.1]: Constructing a set based on PLC
2015-05-08T19:27:48.005207+00:00 app[bot.1]: Found PLC in set_symbols, passing through.
2015-05-08T19:27:47.891277+00:00 app[bot.1]: Found PLC in set_symbols, passing through.
2015-05-08T19:27:48.002198+00:00 app[bot.1]: Set not found in cache: Planar_Chaos
2015-05-08T19:27:47.890454+00:00 app[bot.1]: Getting card: Damnation PLC
2015-05-08T19:27:47.890681+00:00 app[bot.1]: Constructing a name based on Damnation
2015-05-08T19:27:47.891040+00:00 app[bot.1]: Constructing a set based on PLC
2015-05-08T19:27:47.891539+00:00 app[bot.1]: Constructing an ID from Damnation and Planar_Chaos
2015-05-08T19:27:47.946208+00:00 app[bot.1]: Card not found in cache: Damnation PLC
2015-05-08T19:27:47.889578+00:00 app[bot.1]: Name and set passed in, try getting them directly.
2015-05-08T19:27:48.009758+00:00 app[bot.1]: Calling mtgprice API for set: Planar_Chaos
2015-05-08T19:27:47.946670+00:00 app[bot.1]: Found PLC in set_symbols, passing through.
2015-05-08T19:27:47.946903+00:00 app[bot.1]: Checking if set Planar_Chaos exists in the cache.
2015-05-08T19:27:48.473936+00:00 app[bot.1]:     card = get_card(name, set_name)
2015-05-08T19:27:48.249224+00:00 app[bot.1]: Loading JSON from MTGPrice for: Planar_Chaos
2015-05-08T19:27:48.474014+00:00 app[bot.1]:   File "/app/modules/price.py", line 258, in get_card
2015-05-08T19:27:48.474114+00:00 app[bot.1]:     load_set(construct_set(set_name))
2015-05-08T19:27:48.474192+00:00 app[bot.1]:   File "/app/modules/price.py", line 202, in load_set
2015-05-08T19:27:48.474275+00:00 app[bot.1]:     options={"expires_in": 86400, "add": True}
2015-05-08T19:27:48.475023+00:00 app[bot.1]: HTTPError: 404 Client Error: Not Found
2015-05-08T19:27:48.475163+00:00 app[bot.1]: Exception while searching: 
2015-05-08T19:27:48.474602+00:00 app[bot.1]:     retry=retry)
2015-05-08T19:27:48.474680+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/iron_core.py", line 245, in request
2015-05-08T19:27:48.474776+00:00 app[bot.1]:     r.raise_for_status()
2015-05-08T19:27:48.473688+00:00 app[bot.1]: Traceback (most recent call last):
2015-05-08T19:27:48.473830+00:00 app[bot.1]:   File "/app/modules/price.py", line 309, in price
2015-05-08T19:27:48.474351+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/iron_cache.py", line 128, in put
2015-05-08T19:27:48.474439+00:00 app[bot.1]:     {"Content-Type": "application/json"})
2015-05-08T19:27:48.474516+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/iron_core.py", line 330, in put
2015-05-08T19:27:48.474846+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests/models.py", line 773, in raise_for_status
2015-05-08T19:27:48.474931+00:00 app[bot.1]:     raise HTTPError(http_error_msg, response=self)
2015-05-08T19:27:48.250179+00:00 app[bot.1]: Caching card list for: Planar_Chaos
```

**Comment by skeet70** [comment]
This looks to be an API issue. Most sets with split cards come back from the API like this:

``` json
[
  {
    "mtgpriceID": "Warleader's_HelixDragons_MazefalseNM-M",
    "name": "Warleader's Helix",
    "fairPrice": "$.29"
  },
  {
    "mtgpriceID": "Warped_PhysiqueDragons_MazefalseNM-M",
    "name": "Warped Physique",
    "fairPrice": "$.20"
  },
  {
    "mtgpriceID": "Weapon_SurgeDragons_MazefalseNM-M",
    "name": "Weapon Surge",
    "fairPrice": "$.15"
  },
  {
    "mtgpriceID": "Wear__TearDragons_MazefalseNM-M",
    "name": "Wear \/\/ Tear",
    "fairPrice": "$.90"
  },
  {
    "mtgpriceID": "Wind_DrakeDragons_MazefalseNM-M",
    "name": "Wind Drake",
    "fairPrice": "$.15"
  },
  {
    "mtgpriceID": "Woodlot_CrawlerDragons_MazefalseNM-M",
    "name": "Woodlot Crawler",
    "fairPrice": "$.21"
  },
  {
    "mtgpriceID": "Zhur-Taa_AncientDragons_MazefalseNM-M",
    "name": "Zhur-Taa Ancient",
    "fairPrice": "$.30"
  }
]
```

The response for Planar Chaos has:

``` json
[
  {
    "mtgpriceID": "Dawn_CharmPlanar_ChaosfalseNM-M",
    "name": "Dawn Charm",
    "fairPrice": "$.56"
  },
  {
    "mtgpriceID": "Dead_//_GonePlanar_ChaosfalseNM-M",
    "name": "Dead // Gone",
    "fairPrice": "$0.09"
  },
  {
    "mtgpriceID": "Dead__GonePlanar_ChaosfalseNM-M",
    "name": "Dead // Gone",
    "fairPrice": "$.17"
  }
]
```

The `//` in the card title is being interpreted as part of the URL when it's being added to the cache, which breaks the entire set going in. There are several ways to handle this, but for now it's probably going to stay broken.

**Comment by skeet70** [comment]
We just skipped adding IDs with // in them to the cache at all. This is dirty, but quick and fixes most situations that could come up. The // cards themselves still won't work though.
